language: node_js
node_js:
  - 6
  - 8
  - 9
  - 10
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Preparation of npm
      node_js: node
      script: "./release-script.sh"
    - stage: npm release
      node_js: node
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: abe@enzou.tokyo
        on:
          tags: true
        api_key:
          secure: GR+STCNpSFM2h4HRlydLcsppTjufMt28A4dzqjJLvE5YSlj5ULoOj+49PfL7vVkkMcv5JtteA1lQPtkcLrumO/hh9uyLWEpKukAkUywLAg1thgltwj4k226klJkcdpAhReb3XQQ7+FtZcbZsj8OFIWDBPDN2FRnTXLowZqOLh1BbSWXu4+pqqzyDTFqqF4EtVkeuDF5LPwzJHuw+g9G88iv5PCybs6l6k77q/O3RfCWXw1IYUJmhuwCbP2MYBQxA2qIS0GZ/VtU3eLzDf5Dx//fnjYGgEA0Of8trmvRDGyV9xVqoWtXxS3GhsbhwWwTtft/Y6yc/33VPBFaOFvgXrDny+faB4Yxpwi+RKVoDSoOvYlJ/Np/e1MkVtcMkYZZ2iY6XcFg+gfpXDFW/s06mzoUgRxeTqZcRFr5a4Y39+qEyY6QjjV+NN9hg3Qct+zOgjdLQD06IKqE1MW6pkb5HRgIGvmo+VKw++d6AI/x7h9g7zZhSlinkwtPHjRBzVZqC/MrlhXVNwEJXlbRuOsSmvBSn7iYl8iYQeSNLhCuKWsWXFHkCwLCH6g7Q0etQAo8mepbAcY7mbVCrfk/MzCQQ4JXTZmWxpjBj98ju9c1vsRe1ZCNzckRflVtso1TOtj2w3rU4S4oOfz1Ebgm6RCkQATxbNT7L6+NMbA9OYB5xH4I=
